# Generated by Django 5.0.1 on 2024-02-27 20:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportedCv',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('basic_information', models.JSONField()),
                ('education', models.JSONField()),
                ('experiences', models.JSONField()),
                ('licenses', models.JSONField()),
                ('projects', models.JSONField()),
                ('hide_basic_information_items', models.JSONField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='exportedcv',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_export'),
        ),
    ]
