version: '3.8'   
name: linkedincv-dev
services:
  linkedincv-dev:
    build: .
    restart: unless-stopped
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - "4949:4949"
      - "80:80"
    environment:
      ENVIROMENT: dev