# Generated by Django 5.0.1 on 2024-02-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilehtml',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='userprofilehtml',
            name='user',
            field=models.TextField(unique=True),
        ),
    ]
