# Generated by Django 5.0.1 on 2024-02-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercookie',
            name='default_username',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
