# Generated by Django 5.0.1 on 2024-02-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_userprofilehtml_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilehtml',
            name='cookie',
            field=models.TextField(default='', max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofilehtml',
            name='user',
            field=models.TextField(max_length=255),
        ),
    ]
