# Generated by Django 5.0.1 on 2024-02-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_alter_userprofilehtml_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercookie',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofilehtml',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
